services:
  youtube-notification-service:
    build: .
    container_name: youtube-notification-service
    environment:
      - YOUTUBE_CHANNEL_ID=
      - WEBHOOK_URL=
      - CHECK_INTERVAL=15
      - NOTIFY_TITLE=""
      - DOWNLOAD_VIDEO=false
    volumes:
      - notification-history:/usr/src/app/notification-history.json
      - /local/dir/here:/usr/src/app/downloads

volumes:
  notification-history:
