services:
  youtube-notification-service:
    build: .
    container_name: youtube-notification-service
    environment:
      - YOUTUBE_CHANNEL_ID=
      - WEBHOOK_URL=
      - CHECK_INTERVAL=15
      - NOTIFY_TITLE=""
    volumes:
      - notification-history:/usr/src/app/notification-history.json

volumes:
  notification-history:
